export const PlatformVerificationStatus = {
    PLATFORM_UNVERIFIED: 0,
    PLATFORM_TAMPERED: 1,
    PLATFORM_SOFTWARE_VERIFIED: 2,
    PLATFORM_HARDWARE_VERIFIED: 3,
    PLATFORM_NO_VERIFICATION: 4,
    PLATFORM_SECURE_STORAGE_SOFTWARE_VERIFIED: 5
}