export const SignedMessage_MessageType = {
    LICENSE_REQUEST: 1,
    LICENSE: 2,
    ERROR_RESPONSE: 3,
    SERVICE_CERTIFICATE_REQUEST: 4,
    SERVICE_CERTIFICATE: 5,
    SUB_LICENSE: 6,
    CAS_LICENSE_REQUEST: 7,
    CAS_LICENSE: 8,
    EXTERNAL_LICENSE_REQUEST: 9,
    EXTERNAL_LICENSE: 10
}